name: Update API from Latest Tag

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 8 * * *'  

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of cyz2json
        uses: actions/checkout@v4

      - name: Installer .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Fetch latest tag of CyzFile-API
        run: |
          REPO_OWNER="CytoBuoy"
          REPO_NAME="CyzFile-API"
          TARGET_DIR=Cyz2Json/CyzFile-API

          # Clone API repo
          git clone --depth 1 --branch $(git ls-remote --tags --sort=-v:refname https://github.com/$REPO_OWNER/$REPO_NAME.git | head -n 1 | cut -d'/' -f3) https://github.com/$REPO_OWNER/$REPO_NAME.git external-repo

          # Compile the API (only CyzFile)
          cd external-repo
          dotnet restore
          dotnet publish CyzFile/CyzFile.vbproj --configuration Release --framework net8.0

          # Copy compiled files to target dir
          mkdir -p ../$TARGET_DIR
          cp -r AnyCPU/Release/net*/publish ../$TARGET_DIR/

          # Clean cloned repo
          cd ..
          rm -rf external-repo

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatic update of CyzFile-API from latest tag"
          git push
