name: Update API from Latest Tag

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 8 * * *'  

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of cyz2json
        uses: actions/checkout@v4

      - name: Installer .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Fetch latest tag of CyzFile-API
        run: |
          REPO_OWNER="CytoBuoy"
          REPO_NAME="CyzFile-API"
          BASE_TARGET_DIR="Cyz2Json"

          # Clone API repo
          git clone https://github.com/$REPO_OWNER/$REPO_NAME.git external-repo

          # Path to temporary dir (for build)
          TEMP_DIR="$GITHUB_WORKSPACE/temp_dir"
          mkdir -p "$TEMP_DIR"
          
          cd external-repo

          # Get latest tag
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag found : $LATEST_TAG"

          # Path to result dir
          FULL_TARGET_DIR="$GITHUB_WORKSPACE/$BASE_TARGET_DIR/$LATEST_TAG"

          # Checkout the tag
          git checkout $LATEST_TAG

          # Compile the API (only CyzFile)
          dotnet restore

          # Build + publish with custom MSBuild properties
          dotnet msbuild CyzFile/CyzFile.vbproj -target:Publish -p:OutputPath=$TEMP_DIR/ -p:Configuration=Release -p:TargetFramework=net8.0

          echo "Content of $TEMP_DIR :"
          ls -R $TEMP_DIR
          
          # Make dir to store publish result and copy
          mkdir -p "$FULL_TARGET_DIR"

          # Path to publish dir
          PUBLISH_DIR="$TEMP_DIR/publish"

          echo "Chemin source : $PUBLISH_DIR"
          echo "Chemin destination : $FULL_TARGET_DIR"
          
          if [ -d "$PUBLISH_DIR" ]; then
            echo "Copie des fichiers depuis $PUBLISH_DIR vers $FULL_TARGET_DIR"
            cp -r "$PUBLISH_DIR"/* "$FULL_TARGET_DIR/"
          else
            echo "Erreur : Le dossier source $PUBLISH_DIR n'existe pas."
            exit 1
          fi
      
          # Clean temporary folders
          rm -rf "$TEMP_DIR"
          rm -rf external-repo

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatic update of CyzFile-API from latest tag"
          git push
