name: Test Cyz2Json after changes

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  schedule:
    - cron: '00 2 16 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Install OpenCvSharp dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        # Dependencies needed on Linux
        # They need to be installed here to avoid compiling the project with outdated versions which won't be found locally
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libtesseract-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswscale-dev \
          libopenexr-dev \
          libtiff-dev
        
    - name: Set RID
      id: set-rid
      shell: bash
      run: |
        case "${{ matrix.os }}" in
          windows-latest) echo "rid=win-x64" >> $GITHUB_OUTPUT ;;
          ubuntu-latest) echo "rid=linux-x64" >> $GITHUB_OUTPUT ;;
          macos-latest)
            if [ "$(uname -m)" = "arm64" ]; then
              echo "rid=osx-arm64" >> $GITHUB_OUTPUT
            else
              echo "rid=osx-x64" >> $GITHUB_OUTPUT
            fi
            ;;
        esac

    - name: Restore dependencies and Build
      shell: bash
      run: |
        dotnet restore
        dotnet build --no-restore -p:OutputPath=./bin/
        
    - name: Publish
      shell: bash
      run: |
        dotnet publish \
          -c Release \
          -r ${{ steps.set-rid.outputs.rid }} \
          -p:OutputPath=./bin/${{ steps.set-rid.outputs.rid }}/

    - name: Create symlink for OpenCvSharpExtern.dylib
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        publish_dir="Cyz2Json/bin/${{ steps.set-rid.outputs.rid }}/publish"
        cd $publish_dir/
        # Create symlink to redirect calls to OpenCvSharpExtern.dylib to libOpenCvSharpExtern.dylib (the file actually created)
        ln -sf libOpenCvSharpExtern.dylib OpenCvSharpExtern.dylib
        cd ../../..

    - name: Run executable
      shell: bash
      run: |
        exmpl_path="examples/data/"
        file="$exmpl_path/SeineMO_Microphoto_station02_flr26_2ul_8min 2024-05-04 07h54_SubSet.cyz"
        dll_path="Cyz2Json/bin/${{ steps.set-rid.outputs.rid }}/publish/Cyz2Json.dll"
        bn=$(basename "$file")
        # if macOS, use env var to look for native dependencies inside publish dir (or else it will throw an error)
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          export DYLD_FALLBACK_LIBRARY_PATH=$(dirname $dll_path)
        fi
        dotnet $dll_path "$file" --imaging-set-information --image-processing --output $exmpl_path/"$bn".json
        echo "File successfully converted !"
