name: Test Cyz2Json after changes

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  schedule:
    - cron: '00 2 16 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Install OpenCvSharp dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        # Dependencies needed on Linux
        # They need to be installed here to avoid compiling the project with outdated versions which won't be found locally
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libtesseract-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswscale-dev \
          libopenexr-dev \
          libtiff-dev
        
    - name: Set RID
      id: set-rid
      shell: bash
      run: |
        case "${{ matrix.os }}" in
          windows-latest) echo "rid=win-x64" >> $GITHUB_OUTPUT ;;
          ubuntu-latest) echo "rid=linux-x64" >> $GITHUB_OUTPUT ;;
          macos-latest)
            if [ "$(uname -m)" = "arm64" ]; then
              echo "rid=osx-arm64" >> $GITHUB_OUTPUT
            else
              echo "rid=osx-x64" >> $GITHUB_OUTPUT
            fi
            ;;
        esac

    - name: Restore dependencies and Build
      shell: bash
      run: |
        dotnet restore
        dotnet build --no-restore -p:OutputPath=./bin/
        
    - name: Publish
      shell: bash
      run: |
        dotnet publish \
          -c Release \
          -r ${{ steps.set-rid.outputs.rid }} \
          -p:OutputPath=./bin/${{ steps.set-rid.outputs.rid }}/

    - name: Create symlink for OpenCvSharpExtern.dylib
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        publish_dir="Cyz2Json/bin/${{ steps.set-rid.outputs.rid }}/publish"
        cd $publish_dir/
        # Create symlink to redirect calls to OpenCvSharpExtern.dylib to libOpenCvSharpExtern.dylib (the file actually created)
        ln -sf libOpenCvSharpExtern.dylib OpenCvSharpExtern.dylib

    - name: Fix library path (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        publish_dir="Cyz2Json/bin/${{ steps.set-rid.outputs.rid }}/publish"
        cd $publish_dir/
        # Native libs are searched in @executable_path/../libs/ by default but this folder doesn't exist
        # Get dependencies to fix (starting with @executable_path/../libs)
        deps=$(
          otool -L OpenCvSharpExtern.dylib |
          grep "@executable_path/../libs/" |
          sed -E 's/\(.*\)//' |
          awk -F'/' '{print $NF}' |
          sort |
          uniq
        )
        # Fix paths
        for dep in $deps; do
          if [ -n "$dep" ]; then
            echo "Fixing path for $dep..."
            install_name_tool -change "@executable_path/../libs/$dep" "@executable_path/$dep" OpenCvSharpExtern.dylib
          fi
        done
        echo "New libs path"
        otool -L OpenCvSharpExtern.dylib

    - name: Run executable
      shell: bash
      run: |
        exmpl_path="examples/data/"
        file="$exmpl_path/sample.cyz"
        dll_path="Cyz2Json/bin/${{ steps.set-rid.outputs.rid }}/publish/Cyz2Json.dll"
        bn=$(basename "$file")
        dotnet $dll_path "$file" --imaging-set-information --image-processing --output $exmpl_path/"$bn".json
        echo "File successfully converted !"
